name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        apt-get update && apt-get install -y sudo git curl
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh

    - name: Build and run all components
      run: |
        cd testplans/spid-cie-oidc/implementations/spid-cie-oidc-django/
        chmod +x build_and_run.sh
        ./build_and_run.sh

    - name: Wait for the server to start
      run: sleep 15

    - name: Run script to send API test requests
      run: |
        cd testplans/spid-cie-oidc/implementations/spid-cie-oidc-django/
        docker exec spid-cie-oidc-django-burpsuite-1 /run_tests.sh /test1.json
        docker cp spid-cie-oidc-django-burpsuite-1:/output.json output.json
      
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: output.txt
        path: testplans/spid-cie-oidc/implementations/spid-cie-oidc-django/output.json
